### ISSUE TITLE
Update to v2.2 in anaconda

### ISSUE THREAD

**Issue by grgmiller** [NREL/pysam#76] opened 2021-01-21 01:21 UTC
The NREL channel for Anaconda still contains v2.1.4 as the latest version for nrel-pysam and nrel-pysam-stubs. Currently v2.2 is only available through pip. 

https://anaconda.org/nrel/nrel-pysam 

Thank you!

**Comment by dguittet** [comment] 2021-01-23 00:57
I've uploaded Version 2.2.0 to conda for

- Linux for Python 3.6-3.9
- Mac, 3.6 - 3.9

Windows will take some more time as I wait for network issues to be resolved for my remote VM

Closing as duplicate of https://github.com/NREL/pysam/issues/68

**Closed by dguittet** 2021-01-23 00:57 UTC
